name: myst-exec
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - pip
  - pip:
      - mystmd==1.6.0
      - numpy
      - scipy
      - pandas
      - matplotlib
      - ase
      - jupytext
